apiVersion: v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: case
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: locust-monitor
  namespace: case
  labels:
    app: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  endpoints:
  - port: web
    path: /stats/requests
    interval: 15s