apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"backend","color":"blue"},"name":"backend","namespace":"case"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend","color":"blue"}},"template":{"metadata":{"annotations":{"ad.datadoghq.com/backend.checks":"{\"openmetrics\":{\"instances\":[{\"openmetrics_endpoint\":\"http://%%host%%:3000/metrics\",\"namespace\":\"backend\"}]}}","ad.datadoghq.com/backend.logs":"[{\"source\":\"nodejs\",\"service\":\"backend\"}]"},"labels":{"app":"backend","color":"blue"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"3000"},{"name":"AWS_REGION","valueFrom":{"configMapKeyRef":{"key":"AWS_REGION","name":"env-config"}}},{"name":"DDB_TABLE","valueFrom":{"configMapKeyRef":{"key":"DDB_TABLE","name":"env-config"}}},{"name":"DD_ENV","value":"prod"},{"name":"DD_SERVICE","value":"backend"},{"name":"DD_VERSION","value":"0.1.0"},{"name":"DD_LOGS_INJECTION","value":"true"},{"name":"DD_TRACE_ENABLED","value":"true"},{"name":"DD_TRACE_AGENTLESS","value":"true"},{"name":"DD_SITE","valueFrom":{"configMapKeyRef":{"key":"DD_SITE","name":"env-config"}}},{"name":"DD_API_KEY","valueFrom":{"secretKeyRef":{"key":"api-key","name":"datadog"}}},{"name":"OTEL_TRACE_ENABLED","value":"true"},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://tempo:4318/v1/traces"},{"name":"SERVICE_NAME","value":"case-backend"},{"name":"SERVICE_VERSION","value":"0.1.0"}],"image":"case-backend:latest","imagePullPolicy":"Never","name":"backend","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"serviceAccountName":"backend-sa"}}}}
  creationTimestamp: "2025-10-26T14:33:00Z"
  generation: 1
  labels:
    app: backend
    color: blue
  name: backend
  namespace: case
  resourceVersion: "15152"
  uid: a3758695-5d92-4f46-8765-a4ff24bdc5c1
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
      color: blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/backend.checks: '{"openmetrics":{"instances":[{"openmetrics_endpoint":"http://%%host%%:3000/metrics","namespace":"backend"}]}}'
        ad.datadoghq.com/backend.logs: '[{"source":"nodejs","service":"backend"}]'
      creationTimestamp: null
      labels:
        app: backend
        color: blue
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: env-config
        - name: DDB_TABLE
          valueFrom:
            configMapKeyRef:
              key: DDB_TABLE
              name: env-config
        - name: DD_ENV
          value: prod
        - name: DD_SERVICE
          value: backend
        - name: DD_VERSION
          value: 0.1.0
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_TRACE_ENABLED
          value: "true"
        - name: DD_TRACE_AGENTLESS
          value: "true"
        - name: DD_SITE
          valueFrom:
            configMapKeyRef:
              key: DD_SITE
              name: env-config
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: datadog
        - name: OTEL_TRACE_ENABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://tempo:4318/v1/traces
        - name: SERVICE_NAME
          value: case-backend
        - name: SERVICE_VERSION
          value: 0.1.0
        image: case-backend:latest
        imagePullPolicy: Never
        name: backend
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: backend-sa
      serviceAccountName: backend-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-10-26T14:33:00Z"
    lastUpdateTime: "2025-10-26T14:33:03Z"
    message: ReplicaSet "backend-b8cf787b7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-10-26T17:33:52Z"
    lastUpdateTime: "2025-10-26T17:33:52Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
